version: '3.8'

services:
  web:
    build: .
    image: tomcat-local:11.0.6-jre21
    container_name: tomcat-local
    ports:
      - '9292:8080'
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:alpine3.21-jdk21
    container_name: jenkins
    ports:
      - '9191:8080'
      - '50000:50000'
    restart: on-failure
